swagger: '2.0'
info:
  version: '1.0'
  title: L2VpnService Sbi Adapter Interface
  description: Orchestrator SDN-O SBI Reference V1.0-L2VPN
host: sdno.openo.org
basePath: /openoapi/sbi-l2vpn-vpws/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
 /l2vpn_vpwss:
    post:
      summary: Create L2Vpn Connection
      description: Creates a L2Vpn Connection instance, need to pass in controller id
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: X-Driver-Parameter
          in: header
          description: Controller ID, the format is X-Driver-Parameter:extSysID={ctrlUuid}.
          required: true
          type: string
        - name: l2vpnVpws
          in: body
          description: L2Vpn Connection
          required: true
          schema:
            $ref: '#/definitions/L2Vpn'
      responses:
        201:
          description: create L2Vpn connection.
          schema:
            $ref: '#/definitions/L2Vpn'
        400:
          description: create L2Vpn Instances failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: create L2Vpn Instances failure as can't reach server.
        500:
          description: create L2Vpn Instances failure as inner error.

 /l2vpn_vpwss/{vpnid}:
    delete:
      summary: Delete a L2Vpn Connection
      description: Delete a L2Vpn Connection, need to pass in controller id and vpn id
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: X-Driver-Parameter
          in: header
          description: Controller ID, the format is X-Driver-Parameter:extSysID={ctrlUuid}.
          required: true
          type: string
        - name: vpnid
          in: path
          description: L2Vpn Connection uuid
          required: true
          type: string
      responses:   
        200:
          description: Delete a L2Vpn connection
          schema:
            $ref: '#/definitions/L2Vpn'
        400:
          description: delete a L2Vpn Instance failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: delete a L2Vpn Instance failure as can't reach server.
        500:
          description: delete a L2Vpn Instance failure as inner error.

    get:
      summary: Query a L2Vpn Connection
      description: Query a L2Vpn Connection, need to pass in controller id and vpn id
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: X-Driver-Parameter
          in: header
          description: Controller ID, the format is X-Driver-Parameter:extSysID={ctrlUuid}.
          required: true
          type: string
        - name: vpnid
          in: path
          description: L2Vpn Connection uuid
          required: true
          type: string
      responses:
        200:
          description: Query a L2Vpn connection 
          schema:
            $ref: '#/definitions/L2Vpn'
        400:
          description: query a L2Vpn failure as parameters invalid.
        401:
          description: unauthorized.
        404:
          description: query a L2Vpn failure as can't reach server.
        500:
          description: query a L2Vpn failure as inner error.

    put:
      summary: Update a L2Vpn Connection
      description: Update a L2Vpn Connection, need to pass in controller id and vpn id
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: X-Driver-Parameter
          in: header
          description: Controller ID, the format is X-Driver-Parameter:extSysID={ctrlUuid}.
          required: true
          type: string
        - name: vpnid
          in: path
          description: L2Vpn Connection uuid
          required: true
          type: string
        - name: l2vpnVpws
          in: body
          description: L2Vpn Connection instance
          required: true
          schema:
            $ref: '#/definitions/L2Vpn'
      responses:
        200:
          description: Update a L2Vpn connection 
          schema:
            $ref: '#/definitions/L2Vpn'
        400:
          description: L2Vpn resource provided in body is missing with required properties.
        401:
          description: Unauthorized
        404:
          description: not found
        500:
          description: L2Vpn service failed to process the request.

definitions:

  L2Vpn:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        description: L2Vpn Connection UUID
        format: uuid
      name:
        type: string
        description: L2Vpn Connection name
      tenantId:
        type: string
        description: tenant UUID
      description:
        type: string
        description: description of L2Vpn Connction
      topology:
        type: string
        description: This identify the connection mode of vpns, including none, hub-spoke and full-mesh
      adminStatus:
        type: string
        enum:
        - adminUp
        - adminDown
        description: L2VPN Connection management status, including adminUp and adminDown
      operStatus:
        type: string
        enum: 
        - operateUp 
        - operateDown
        description: The running status of connection in controller, the adapter need fill this parameter, including operateUp and operateDown
      tunnelService:
        $ref: '#/definitions/TunnelService'
      mtu:
        type: integer
        description: Mtu of L2Vpn business, range from 46 to 9600
        format: int16
      acs:
        $ref: '#/definitions/L2Acs'
      ctrlWord: 
        type: string
        enum:
          - disable
          - enable
        description: Control Word type, including disable and enable
      pwTrails:
        $ref: '#/definitions/PwTrails'
      signalingType:
        type: string
        enum:
          - static
          - ldp
          - rsvp-te
          - sr-te
        description: Signaling Type of L2Vpn, including static,ldp and rsvp-te
      encapsulation:
        type: string
        enum:
          - ethernet
          - vlan
        description: Encapsulation Type of L2Vpn, including eth and vlan
  PwTrails:
    type: object
    properties:
      pwTrail:
        type: array
        description: private wire service
        items:
          $ref: '#/definitions/PwTrail'
  PwTrail:
    type: object
    required:
      - id 
    properties:
      id:
        type: string
        format: maxLen36
        description: uuid of private wire
      ingressNeId:
        type: string
      egressNeId:
        type: string
      pws:
        $ref: "#/definitions/Pws"
      enableControlWord:
        type: boolean
      accessMode:
        type: string
        enum:
        - raw
        - tag
      encapsulationType:
        type: string
        enum:
        - ethernet
        - vlan
      protectionRole:
        type: string
        enum: 
          - primary
          - secondary
          - dni
          - dni-ac
          - dni-pw
        description: protection role, including primary, backup      
  TunnelService:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        enum:
          - auto-select
          - mpls-te
          - vxlan
          - gre
        description: Type of tunnel policy, including auto-select、mpls-te、vxlan、gre
      autoSelect:
        $ref: '#/definitions/AutoSelectPolicy'
      mplsTe:
        $ref: '#/definitions/MplsTePolicy'
      particularConstraints:
        $ref: '#/definitions/ParticularConstraints'
  AutoSelectPolicy:
    type: object
    required:
      - loadBalanceNumber
    properties:
      loadBalanceNumber:
        type: integer
        description: Auto Select tunnel Load Number range from 1 to 32
        format: int32
      autoSelectTunnels:
        $ref: '#/definitions/AutoSelectTunnels'
  AutoSelectTunnels:
    type: object
    required:
      - autoSelectTunnel
    properties: 
      autoSelectTunnel:
        type: array
        items:
            $ref: '#/definitions/AutoSelectTunnel'
  AutoSelectTunnel:
    type: object
    required:
      - type
    properties: 
      type:
        type: string
        enum:
          - ldp
          - te
          - gre
        description: Tunnel type of Auto select tunnel policy
      priority:
        type: integer
        description: Tunnel priority of Auto select tunnel policy
        format: int32
  ParticularConstraints:
    type: object
    required:
      - particularConstraint
    properties:
      particularConstraint:
        type: array
        description: List of particular constraints
        items:
          $ref: '#/definitions/ParticularConstraint'
  ParticularConstraint:
    type: object
    required:
      - ingressNe
    properties:
      ingressNe:
        type: string
        description: Ingress node of tunnel
        format: string
      egressNe:
        type: string
        description: Egress node of tunnel
        format: string
      type:
        type: string
        enum:
          - binding
          - particular-mpls-te-tunnel
        description: Type of tunnel constraint including binding and particular-mpls-te-tunnel
      bindingTunnelMo:
        type: array
        description: List of binding tunnel
        items:
          $ref: '#/definitions/BindingTunnel'
      mplsTe:
        $ref: '#/definitions/MplsTePolicy'
  MplsTePolicy:
    type: object
    required:
      - signalType
    properties:
      signalType:
        type: string
        enum:
          - rsvp-te
          - sr-te
          - static-lsp
        description: Tunnel type of Manual Select, including rsvp-te、sr-te、static-lsp
      manageProtocol:
        type: string
        description: Manage protocol, including netconf、pcep
      sharing:
        type: boolean
        description: Whether is shared, including true、false
      besteffort:
        type: boolean
        description: Whether is best effort, including true、false
      bandwidth:
        type: integer
        description: Tunnel bandwidth in kbps
        format: int32
      coRoute:
        type: boolean
        description: Whether to re Route, including true、false
      bfdEnable:
        type: boolean
        description: Whether to enable BFD Protocol, including true、false
      pathConstraint:
        $ref: '#/definitions/PathConstraint'
      pathProtectPolicy:
        $ref: '#/definitions/PathProtectPolicy'
  BindingTunnel:
    type: object
    properties:
      name:
        type: string
      uuid:
        type: string
        
  PathConstraint:
    type: object
    required:
      - setupPriority
    properties: 
      setupPriority:
        type: integer
        description: Setup priority of tunnel route constraints, range from 0 to 7
        format: int32
      holdupPriority:
        type: integer
        description: Holdup priority of tunnel route constraints, range from 0 to 7
        format: int32
      latency:
        type: integer
        description: Latency priority of tunnel route constraints, range from 0 to 60000000
        format: int32
  PathProtectPolicy:
    type: object
    required:
      - type
    properties: 
      type:
        type: string
        description: Type of tunnel protection policy 
      hotStandbyEnable:
        type: boolean
        description: Whether to enable hotstandby in tunnel protection, including true、false
      revertive:
        type: boolean
        description: Whether to revertive in tunnel protection including true、false
      bandwidthMode:
        type: string
        description: Bandwidth mode of tunnel protection including original-bandwidth、dynamic-bandwidth
      wtr:
        type: integer
        description: Wtr time of tunnel protection revertive in us, range from 0 to 60000000
        format: int64
  L2Acs:
    type: object
    required: 
      - ac
    properties:
      ac:
        type: array
        items: 
          $ref: '#/definitions/L2Ac'
        description: Layer2 Vpn Access Point configuration
  L2Ac:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      tenantId:
        type: string
        format: uuid
      localName:
        type: string
      description:
        type: string
      neId:
        type: string
        format: uuid
      ltpId:
        type: string
        format: uuid
      adminStatus:
        type: string
        enum:
          - adminUp
          - adminDown
      operStatus:
        type: string
        enum: 
          - operateUp 
          - operateDown
      l2Access:
        $ref: '#/definitions/L2Access'
      inboundQosPolicyId:
        type: string
      outboundQosPolicyId:
        type: string
      inboundQueuePolicyId:
        type: string
      outboundQueuePolicyId:
        type: string
      inboundQosIfPhb:
        $ref: '#/definitions/QosIfPhb'
      outboundQosIfPhb:
        $ref: '#/definitions/QosIfPhb'
      upstreamBandwidth:
        $ref: '#/definitions/QosIfCar'
      downstreamBandwidth:
        $ref: '#/definitions/QosIfCar'
      externalQosPolicyId:
        type: string
        description: Id of External Qos Policy
      overrideFlows:
        $ref: '#/definitions/OverrideFlows'
      acRole:
        type: string
        enum:
        - UNI
        - NNI
  OverrideFlows:
    type: object
    required:
      - overrideFlow
    properties:
      overrideFlow:
        type: array
        description: Bandwidth Configuration of Flow
        items:
          $ref: '#/definitions/OverrideFlow'
  OverrideFlow:
    type: object
    required:
      - externalFlowId
    properties:
      externalFlowId:
        type: string
        description: Flow ID in controller
      name:
        type: string
        description: Flow name in controller.
      direction:
        type: string
        enum:
        - ingress
        - egress
        description: Direction of flow, including ingress, egress
      car:
        $ref: '#/definitions/QosIfCar'
  QosIfCar:
    type: object
    required:
      - enable
      - cir
      - pir
    properties:
      enable: 
        type: boolean
        description: Whether to enable car configuration, including true、false
      cir:
        type: integer
        description: Committed speed in kbps
        format: int64
      pir:
        type: integer
        description: Peak speed in kbps
        format: int64
      cbs:
        type: integer
        description: Committed burst Size in  bytes
        format: int64
      pbs:
        type: integer
        description: Peak burst Size in bytes
        format: int64
      carServiceClasses:
        type: array
        items:
          $ref: "#/definitions/CarServiceClass"
  CarServiceClass:
    type: object
    properties:
      serviceClass:
        type: string
        enum:
          - BE
          - AF1
          - AF2
          - AF3
          - AF4
          - EF
          - CS6
          - CS7
      color:
        type: string
        enum:
          - green
          - yellow
          - red
      passOrDiscard:
        type: string
        enum:
          - pass
          - discard
      flowColor:
        type: string
        enum: 
          - GREEN
          - YELLOW
          - RED
  Pws:
    type: object
    required: 
      - uuid
    properties:
      uuid:
        type: string
        description: uuid of private wire service
      pws:
        type: array
        description: private wire service
        items:
          $ref: '#/definitions/Pw'
  Pw:
    type: object
    required:
      - id 
    properties:
      id:
        type: string
        format: maxLen36
        description: uuid of private wire
      name:
        type: string
        description: name of private wire
      description:
        type: string
        description: description of private wire
      neId:
        type: string
        format: maxLen36
        description: real device uuid allocated by sdno
      peerAddress:
        type: string
        description: remote ipaddress
      vcid:
        type: string
      tunnelPolicy:
        $ref: "#/definitions/TunnelService"
      tunnelId:
        type: string
        description: tunnel id
  L2Access:
    type: object
    properties:
      accessType:
        type: string
        enum:
          - port
          - dot1q
          - qing
      dot1qVlanBitmap:
        type: string
        description: 1-4095
      qinqSvlanBitmap:
        type: string
      qinqCvlanBitmap:
        type: string
      accessAction:
        type: string
        enum:
          - nop
          - untag
          - stacking
          - pvlan
          - swap
          - pass
      vlanActionValue:
        type: string
  QosIfPhb:
    type: object
    properties:
      trust8021p:
        type: boolean
      trustUpstream:
        type: boolean
      phbMap:
        type: boolean